const CFG={v:'v3.5',api:'https://script.google.com/macros/s/AKfycbwiM61R-bfvWbbkciZBDYorbx9F3hgOXU85f5lyuC78kB1zJe1B4MmmHLw6eVk-XDeS/exec',sheet:'https://docs.google.com/spreadsheets/d/1gJpbr_PZXUoU3smlli7DsJPWUJurqCOZxWb8Ui15YqA/edit',repo:'https://github.com/cinaedvsstudios/actarium',live:'https://cinaedvsstudios.github.io/actarium/',fit:'https://cinaedvsstudios.github.io/chrisfit/',viat:'https://cinaedvsstudios.github.io/Viaticum/'};
const S={view:'today',date:iso(new Date()),filter:'all',theme:localStorage.getItem('actarium.theme')||'dark',menu:false,modal:null,sel:new Set(),data:{tasks:[],reminders:[],apps:[],appFeed:[],viaticumEvents:[],schedule:[]},sync:'Loading…'};
document.documentElement.dataset.theme=S.theme;window.addEventListener('DOMContentLoaded',init);
async function init(){render();try{S.data=norm(await get('bootstrap'));S.sync='Live Sheet connection'}catch(e){console.warn(e);S.data=demo();S.sync='Demo / local view'}render()}
async function get(action){const u=new URL(CFG.api);u.searchParams.set('action',action);const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();if(j.success===false)throw Error(j.error||'backend');return j}
async function post(action,payload={}){try{await fetch(CFG.api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})})}catch(e){console.warn(e)}}
function norm(d){return{tasks:(d.tasks||[]).map(task),reminders:(d.reminders||[]).map(rem),apps:(d.apps||[]).map(app).filter(a=>/^active$/i.test(a.status||'Active')).sort((a,b)=>a.sortOrder-b.sortOrder),appFeed:(d.appFeed||[]).map(feed),viaticumEvents:(d.viaticumEvents||[]).map(ve),schedule:routine(d.routine||[]).concat((d.schedule||[]).map(sch))}}
function task(r,i=0){const due=date(r.dueDate||r.due_date||r.startDate||r.start_date||r.date)||S.date,start=date(r.startDate||r.start_date||r.dueDate||r.due_date||r.date)||due,end=date(r.endDate||r.end_date||r.dueDate||r.due_date||r.date)||due;return{id:r.id||`T-${i+1}`,title:r.title||'Untitled task',project:r.project||r.area||'General',source:r.source||'Actarium',status:r.status||'Not started',priority:r.priority||'Normal',dueDate:due,startDate:start,endDate:end,recurrence:r.recurrence||'None',repeatUntil:date(r.repeatUntil||r.repeat_until)||'',notes:r.notes||'',completedAt:r.completedAt||r.completed_at||'',taskType:r.taskType||r.task_type||inferType(r)}}
function rem(r,i){return{...task(r,i),id:r.id||`RMD-${i+1}`,taskType:'Reminder'}}
function app(r){return{id:r.id,label:r.label||'App',emoji:r.emoji||'🔗',url:r.url||'',status:r.status||'Active',sortOrder:+(r.sort_order||r.sortOrder||999),notes:r.notes||'',githubUrl:r.github_url||r.githubUrl||'',group:r.group||group(r)}}
function feed(r){return{sourceApp:r.source_app||r.sourceApp||r.source||'',payload:r.payload_json||r.payload||'',deepLink:r.deep_link||r.deepLink||'',date:date(r.date)||'',title:r.title||''}}
function ve(r){return{date:date(r.date||r.RealDate)||'',status:r.status||r.Status||'Unsure',statusEmoji:r.statusEmoji||r.status_emoji||'🤔',location:r.location||r.Location||'',locationEmoji:r.locationEmoji||r.location_emoji||'📍',event:r.event||r.Event||'',eventEmoji:r.eventEmoji||r.event_emoji||'🎒',schedule:r.schedule||r.Schedule||'',details:r.details||r.Details||'',tripname:r.tripname||''}}
function sch(r){return{title:r.title||'Scheduled item',emoji:r.emoji||'🗓️',days:r.days||'',status:r.status||'Active',details:r.details||''}}
function routine(rows){let ds=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];return rows.flatMap(r=>ds.map((d,i)=>r[d]?{title:r[d],emoji:r.emoji||(i<5?'💼':'🌙'),days:d.slice(0,3),status:'Active'}:null).filter(Boolean))}
function render(){let root=document.getElementById('app');root.innerHTML='';let sh=el('main','app-shell');sh.append(top(),view());root.append(sh);if(S.modal)root.append(modal())}
function top(){let t=el('header','top-bar'),c=el('section','day-card');c.innerHTML=`<div class="top-row"><div class="brand"><img class="logo" src="icon.png"><span class="brand-name">ACTARIUM</span><span class="version">${CFG.v}</span></div><nav class="nav"></nav><div class="actions"></div></div><div class="date-area"><div><p class="eyebrow">${S.view==='today'?'Today':S.view}</p><button class="date-title">${ttl()}</button><div class="date-line">${long(S.date)}</div></div><div class="chips"></div></div>`;[['today','🌅 Today'],['week','🗓️ Week'],['month','🌘 Month'],['tasks','✅ Tasks']].forEach(x=>c.querySelector('.nav').append(btn(x[1],`btn ${S.view===x[0]?'active':''}`,()=>{S.view=x[0];render()})));let a=c.querySelector('.actions');a.append(btn('🧩 Apps','btn',()=>{S.menu=!S.menu;render()}),btn('🗄️ Archive','btn',()=>{S.modal='archive';render()}),btn('➕ Add','btn pulse',()=>{S.modal='task';render()}),btn(S.theme==='light'?'🌙':'☀️','icon',theme),btn('⚙️','icon',()=>{S.modal='settings';render()}),menu());c.querySelector('.date-title').onclick=()=>{S.modal='date';render()};chips().forEach(x=>c.querySelector('.chips').append(x));t.append(c);return t}
function btn(label,cls,fn){let b=el('button',cls),p=split(label);b.type='button';b.innerHTML=`<span class="emoji">${esc(p.e)}</span>${p.t?`<span class="label">${esc(p.t)}</span>`:''}`;b.onclick=fn;return b}
function menu(){let m=el('div',`apps-menu ${S.menu?'open':''}`);['My apps','Admin links','Creative links'].forEach(g=>{let col=el('section');col.innerHTML=`<h3>${g}</h3>`;S.data.apps.filter(a=>(a.group||group(a))===g).forEach(a=>{let r=el('div','app-row');r.innerHTML=`<a class="app-link" target="_blank" href="${a.url}"><span>${a.emoji}</span><span><b>${esc(a.label)}</b><small>${esc(a.notes||'')}</small></span></a>${a.githubUrl?`<a class="git" target="_blank" href="${a.githubUrl}">🐙</a>`:''}`;col.append(r)});m.append(col)});return m}
function chips(){return dayContext(S.date).slice(0,3).map(x=>{let c=el('span','chip');c.textContent=`${x.emoji||'🧭'} ${x.title}`;return c})}
function view(){if(S.view==='tasks')return tasksView();let grid=el('section','view'),left=el('div','col'),right=el('div','col');left.append(appCards(S.view));if(S.view==='today'){let out=S.data.tasks.filter(t=>!arch(t)&&tDate(t)<S.date);if(out.length)right.append(taskSec('🚨 Outstanding',out));right.append(taskSec('✅ Today tasks',filter(S.data.tasks.filter(t=>match(t,S.date)&&!older(t,S.date))),true),taskSec('🔔 Reminders',S.data.reminders.filter(t=>match(t,S.date)&&!arch(t)),'rem'))}else{let [s,e]=range(S.view);right.append(taskSec(`✅ ${S.view} tasks`,S.data.tasks.filter(t=>over(t,s,e)&&!arch(t))),taskSec('🔔 Reminders',S.data.reminders.filter(t=>over(t,s,e)&&!arch(t)),'rem'))}grid.append(left,right);return grid}
function tasksView(){let v=el('section','view'),open=S.data.tasks.filter(t=>!arch(t));v.append(taskSec('🏠 Personal tasks',open.filter(t=>!isWork(t))),taskSec('💼 Work tasks',open.filter(isWork)),taskSec('🔔 Reminders',S.data.reminders.filter(t=>!arch(t)),'rem'));return v}
function appCards(period){let w=el('section','apps-grid');w.append(fitCard(),viatCard(period));return w}
function header(e,t,u,cls){let h=el('div','head');h.innerHTML=`<h3>${e} ${t}</h3><a class="open" target="_blank" href="${u}">🔗 Open</a>`;return h}
function fitCard(){let c=el('article','card fit'),m=fit();c.append(header('🥦','ChrisFit',CFG.fit));let g=el('div','metric-grid');g.append(metric('Daily Summary',[['🥦','Food',m.df],['🔥','Burn',m.db],['📉','Deficit',m.dd]]),metric('Weekly Summary',[['🥦','Food',m.wf],['🔥','Burn',m.wb],['📉','Deficit',m.wd]]));let w=el('div','weight');w.innerHTML=`<b>⚖️ Weight</b><strong>${esc(m.weight)}</strong><span>${esc(m.bmi||'')}</span>`;c.append(g,w);return c}
function viatCard(period){let c=el('article','card viat');c.append(header('🎒','Viaticum',CFG.viat));let ev=events();if(period==='month')c.append(vMonth(ev));else if(period==='week')c.append(vWeek(ev));else c.append(vDay(ev));return c}
function vDay(ev){let e=ev.find(x=>x.date===S.date)||{},wk=ev.filter(x=>inWeek(x.date)),next=wk.find(x=>x.date>=S.date)||{};let w=el('div');let g=el('div','metric-grid');g.append(metric('Daily Summary',[['🤔','',e.status||'Unsure'],['🧸','',e.location||'—'],['🎒','',e.event||'Check Viaticum']]),metric('Weekly Summary',[['🗓️','Items',String(wk.length)],['📍','',places(wk)||'—'],['➡️','',next.event||next.location||'—']]));w.append(g,info('Schedule',e.schedule||e.details||'Open Viaticum and check schedule, maps, paid/unpaid, and codes.'));return w}
function vWeek(ev){let [s,e]=range('week'),rows=ev.filter(x=>x.date>=s&&x.date<=e),w=el('div');w.append(info('Schedule',rows.map(x=>`${x.date.slice(8)} ${x.locationEmoji||'📍'} ${x.location||''} · ${x.eventEmoji||'🎒'} ${x.event||''}`).join('\n')||'No Viaticum items this week.'));return w}
function vMonth(ev){let w=el('div');w.append(info('Month',ev.map(x=>`${x.date.slice(8)} ${x.eventEmoji||'🎒'} ${x.event||x.location||''}`).join('\n')||'No Viaticum month items.'));return w}
function metric(t,rows){let p=el('div','metric');p.innerHTML=`<h4>${t}</h4>`;rows.forEach(r=>{let x=el('div','row');x.innerHTML=`<span>${r[0]}${r[1]?` ${r[1]}`:''}</span><strong>${esc(r[2])}</strong>`;p.append(x)});return p}
function taskSec(title,tasks,filterBar=false){let c=el('section','card tasks'),h=el('div','task-head'),actions=el('div','task-actions');h.innerHTML=`<h2>${title}</h2>`;if(filterBar)actions.append(seg());actions.append(btn('✅ Done selected','btn',doneSelected),btn('➕ New task','btn pulse',()=>{S.modal='task';render()}));h.append(actions);let list=el('div','list');(tasks.length?tasks:[null]).forEach(t=>list.append(t?taskRow(t):empty('No items here.')));c.append(h,list);return c}
function seg(){let s=el('div','seg');[['all','🌐 All'],['personal','🏠 Personal'],['work','💼 Work']].forEach(x=>s.append(btn(x[1],`btn ${S.filter===x[0]?'active':''}`,()=>{S.filter=x[0];render()})));return s}
function taskRow(t){let r=el('article',`task ${done(t)?'done':''}`),cb=el('input','check');cb.type='checkbox';cb.onchange=e=>e.target.checked?S.sel.add(String(t.id)):S.sel.delete(String(t.id));let b=el('button');b.innerHTML=`<h3>${done(t)?'✅ ':''}${isWork(t)?'💼':'🏠'} ${esc(t.title)}</h3><p>${esc(t.project)} · ${esc(t.startDate||t.dueDate)}</p><div class="meta"><span class="pill">${done(t)?'✅ Done':esc(t.status)}</span><span class="pill">${esc(t.priority)}</span></div>`;b.onclick=()=>{S.modal={task:t};render()};r.append(cb,b,btn('🔎','icon',()=>{S.modal={task:t};render()}));return r}
function doneSelected(){let ids=[...S.sel];if(!ids.length)return alert('Tick one or more tasks first.');S.data.tasks=S.data.tasks.map(t=>ids.includes(String(t.id))?{...t,status:'Done',completedAt:new Date().toISOString()}:t);post('markTasksDone',{ids,completedAt:new Date().toISOString()});S.sel.clear();render()}
function modal(){let bg=el('div','modal-bg'),m=el('section','modal');bg.append(m);if(S.modal==='settings')m.innerHTML=`<div class="modal-head"><h2>⚙️ Settings</h2><button class="icon">✕</button></div><div class="modal-body"><a class="settings-link" target="_blank" href="${CFG.sheet}">📊 Open Actarium Sheet</a><a class="settings-link" target="_blank" href="${CFG.repo}">🐙 Open GitHub repo</a><a class="settings-link" target="_blank" href="${CFG.live}">🌐 Open live app</a><p>${CFG.v} · ${S.sync}</p></div>`;else if(S.modal==='archive')m.innerHTML=`<div class="modal-head"><h2>🗄️ Archive</h2><button class="icon">✕</button></div><div class="modal-body"><input placeholder="Search archive">${S.data.tasks.filter(arch).map(t=>`<div class="task done"><span></span><b>${esc(t.title)}</b></div>`).join('')||'<p class="empty">No archive items.</p>'}</div>`;else if(S.modal==='date')m.innerHTML=`<div class="modal-head"><h2>📅 Pick date</h2><button class="icon">✕</button></div><div class="modal-body"><input type="date" value="${S.date}"><button class="btn save">✅ Save</button></div>`;else m.innerHTML=`<div class="modal-head"><h2>➕ New task</h2><button class="icon">✕</button></div><div class="modal-body"><label class="field">Title<input name="title"></label><div class="two"><label class="field">Start<input type="date" name="start" value="${S.date}"></label><label class="field">End<input type="date" name="end" value="${S.date}"></label></div><label class="field">Project<input name="project" value="General"></label><label class="field">Task type<input name="type" value="Personal"></label><label class="field">Notes<textarea name="notes"></textarea></label><button class="btn pulse save">💾 Save</button></div>`;m.querySelector('.modal-head .icon').onclick=()=>{S.modal=null;render()};let save=m.querySelector('.save');if(save)save.onclick=()=>saveModal(m);bg.onclick=e=>{if(e.target===bg){S.modal=null;render()}};return bg}
function saveModal(m){if(S.modal==='date'){S.date=m.querySelector('input').value||S.date;S.modal=null;render();return}let f=n=>m.querySelector(`[name=${n}]`)?.value||'';let t=task({id:`local-${Date.now()}`,title:f('title'),project:f('project'),task_type:f('type'),start_date:f('start'),end_date:f('end'),due_date:f('start'),notes:f('notes')});S.data.tasks.unshift(t);post('saveTask',{task:t});S.modal=null;render()}
function dayContext(d){let tr=trip(d);if(tr)return[tr];let short=parseDate(d).toLocaleDateString('en-GB',{weekday:'short'}).slice(0,3).toLowerCase();return S.data.schedule.filter(x=>!x.days||x.days.toLowerCase().includes(short)).slice(0,2)}
function trip(d){let e=events().find(x=>x.date===d);if(!e)return null;let away=e.location&&!/^(berlin|home)$/i.test(e.location);if(!away&&!/booked|trip/i.test(e.status))return null;return{emoji:'🎒',title:`Trip in progress · ${e.location||e.tripname||e.event||'Trip'}`}}
function events(){return S.data.viaticumEvents.length?S.data.viaticumEvents:demo().viaticumEvents}function fit(){let p=json(S.data.appFeed.find(x=>/chrisfit/i.test(x.sourceApp))?.payload)||{};return{df:p.dailyFood||'0 / 1500',db:p.dailyBurn||'0 / 2500',dd:p.dailyDeficit||'0 / -500',wf:p.weeklyFood||'— / 10500',wb:p.weeklyBurn||'— / 17500',wd:p.weeklyDeficit||'— / -3500',weight:p.weight||'— kg',bmi:p.bmi||''}}
function filter(a){return S.filter==='work'?a.filter(isWork):S.filter==='personal'?a.filter(x=>!isWork(x)):a}function match(t,d){return t.recurrence&&t.recurrence!=='None'?d>=t.startDate&&(!t.repeatUntil||d<=t.repeatUntil):over(t,d,d)}function over(t,s,e){return(t.startDate||t.dueDate)<=e&&s<=(t.endDate||t.dueDate||t.startDate)}function range(v){let d=parseDate(S.date);if(v==='month')return[iso(new Date(d.getFullYear(),d.getMonth(),1)),iso(new Date(d.getFullYear(),d.getMonth()+1,0))];let st=new Date(d);st.setDate(d.getDate()-((d.getDay()+6)%7));return[iso(st),iso(new Date(st.getFullYear(),st.getMonth(),st.getDate()+6))]}function inWeek(d){let r=range('week');return d>=r[0]&&d<=r[1]}function older(t,d){return!arch(t)&&tDate(t)<d}function tDate(t){return t.startDate||t.dueDate||t.endDate||''}function arch(t){return done(t)||/cancel|deleted/i.test(t.status)||!!t.completedAt}function done(t){return/^done$/i.test(t.status)}function isWork(t){return/work/i.test(t.taskType)||/work|zalando|nike|office/i.test(`${t.project} ${t.source} ${t.title} ${t.notes}`)}function places(a){return[...new Set(a.map(x=>x.location).filter(Boolean))].slice(0,2).join(', ')}
function ttl(){return S.view==='week'?'Week':S.view==='month'?parseDate(S.date).toLocaleDateString('en-GB',{month:'long'}):S.view==='tasks'?'Tasks':parseDate(S.date).toLocaleDateString('en-GB',{weekday:'long'})}function long(d){return parseDate(d).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}function theme(){S.theme=S.theme==='light'?'dark':'light';localStorage.setItem('actarium.theme',S.theme);document.documentElement.dataset.theme=S.theme;render()}function split(x){let m=String(x).match(/^(\S+)\s*(.*)$/);return{e:m?.[1]||'',t:m?.[2]||''}}function el(t,c){let x=document.createElement(t);if(c)x.className=c;return x}function empty(t){let p=el('p','empty');p.textContent=t;return p}function info(l,b){let x=el('div','info');x.innerHTML=`<b>${esc(l)}</b><p>${esc(b)}</p>`;return x}function json(s){try{return JSON.parse(s||'{}')}catch{return null}}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function parseDate(v){if(v instanceof Date)return v;let s=String(v||'');if(/^\d{4}-\d{2}-\d{2}$/.test(s)){let[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}let d=new Date(s);return isNaN(d)?new Date():d}function iso(d){let x=parseDate(d);return`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}function date(v){return v?iso(v):''}function inferType(r){return/work|zalando|nike|office/i.test(`${r.project||r.area||''} ${r.source||''} ${r.title||''} ${r.notes||''}`)?'Work':'Personal'}function group(r){return/n26|paypal|drive|gmail|github|netlify/i.test(`${r.label||''} ${r.notes||''}`)?'Admin links':/actarium|chrisfit|viaticum|artifex|onda|organon/i.test(r.label||'')?'My apps':'Creative links'}
function demo(){return{tasks:[task({id:'T1',title:'Connect Actarium to the Sheet backend',project:'Apps',priority:'High',due_date:S.date}),task({id:'T2',title:'Review weekend plans',project:'Travel',status:'Done',due_date:S.date})],reminders:[rem({id:'R1',title:'Check Actarium after deployment',date:S.date})],apps:[['Actarium','📋',CFG.live,'My apps'],['ChrisFit','⚖️',CFG.fit,'My apps'],['Viaticum','🎒',CFG.viat,'My apps'],['GitHub','🐙','https://github.com/','Admin links'],['ChatGPT','💬','https://chatgpt.com/','Creative links']].map((x,i)=>app({id:`A${i}`,label:x[0],emoji:x[1],url:x[2],group:x[3],sort_order:i,status:'Active'})),appFeed:[],schedule:[{emoji:'💼',title:'Work day',days:'Mon,Tue,Wed,Thu,Fri'},{emoji:'🌙',title:'Weekend',days:'Sat,Sun'}],viaticumEvents:[ve({date:S.date,status:'Unsure',location:'Berlin',event:'Check Viaticum',schedule:'Open Viaticum and check schedule, maps, paid/unpaid, and codes.'})]}}
